<?php

namespace AppBundle\Repository;

/**
 * NegocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegocioRepository extends \Doctrine\ORM\EntityRepository
{
}
